name: "Multievent pipeline workflow"


#whenever a push is made to repository on master and test branch
on:
   push:
     branches:
        - developer #hashout temp as creating new files for testing
        - feature
   pull_request:
       branches:
            - developer     
        

jobs:
    on-push:
        if: github.event_name == 'push'
        runs-on: ubuntu_latest
        steps:
            - name: "Running on master/test push"
              run: echo "Running on master/test push"
            
    on-pull_request: #Jon name
        if: github.event_name == 'pull request'
        runs-on: ubuntu_latest
        steps:
          - name: "Running on pull request"
            run: echo "Running on pull request"

 

      
