name: Daily Job

on:
  schedule:
    - cron: '56 15 * * *'

jobs:
    daily-job:
       runs-on: ubuntu-latest

       steps:
         - name: Log daily job message
           run: echo "Daily job done"
       
       